'use client';

import * as React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader } from '@/components/ui/page-header';
import { KpiCard } from '@/components/ui/kpi-card';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { EmptyState } from '@/components/ui/empty-state';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { useAuth } from '@/lib/auth';
import {
  explainBooth,
  fetchBoothPriority,
  fetchD2dInsight,
  fetchVisitorPrep,
  runD2dMining,
  type BoothRisk,
  type IntelTheme,
} from '@/lib/intel';

const sentimentVariant = (s: string) =>
  s?.toLowerCase().includes('neg') ? 'danger' : s?.toLowerCase().includes('pos') ? 'success' : 'muted';

const riskVariant = (score: number) => (score >= 70 ? 'danger' : score >= 45 ? 'warning' : 'success');

function FactorBar({ label, value, weight }: { label: string; value: number; weight: number }) {
  return (
    <div className="mb-1.5">
      <div className="flex justify-between text-[11px] text-muted-foreground">
        <span>
          {label} <span className="opacity-60">·{weight}%</span>
        </span>
        <span className="font-semibold">{value}</span>
      </div>
      <div className="h-1.5 w-full rounded-full bg-muted">
        <div
          className={
            'h-1.5 rounded-full ' +
            (value >= 70 ? 'bg-red-500' : value >= 45 ? 'bg-amber-500' : 'bg-green-500')
          }
          style={{ width: `${Math.min(100, value)}%` }}
        />
      </div>
    </div>
  );
}

export default function IntelPage() {
  const { accessLevel } = useAuth();
  const canEdit = ['edit', 'full'].includes(accessLevel('intel'));
  const qc = useQueryClient();
  const [openBooth, setOpenBooth] = React.useState<BoothRisk | null>(null);

  const { data: insight, isLoading: insightLoading } = useQuery({
    queryKey: ['intel-d2d-latest'],
    queryFn: () => fetchD2dInsight(),
  });
  const { data: booths } = useQuery({
    queryKey: ['intel-booth-priority'],
    queryFn: () => fetchBoothPriority(25),
  });
  const { data: visitors } = useQuery({
    queryKey: ['intel-visitor-prep'],
    queryFn: fetchVisitorPrep,
  });

  const mine = useMutation({
    mutationFn: () => runD2dMining(7),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['intel-d2d-latest'] }),
  });

  const explain = useMutation({ mutationFn: explainBooth });
  const openDrawer = (b: BoothRisk) => {
    setOpenBooth(b);
    explain.reset();
    explain.mutate(b.boothId);
  };

  const themes = (insight?.themes ?? []) as IntelTheme[];
  const shift = insight?.sentimentShift;

  return (
    <>
      <PageHeader
        title="Intel Hub"
        description="D2D sentiment mining, citizen-360 briefs and predictive booth analytics."
        actions={
          canEdit ? (
            <Button variant="outline" disabled={mine.isPending} onClick={() => mine.mutate()}>
              {mine.isPending ? 'Mining…' : 'Run D2D mining'}
            </Button>
          ) : undefined
        }
      />

      <Tabs defaultValue="d2d" className="mt-4">
        <TabsList>
          <TabsTrigger value="d2d">D2D Insights</TabsTrigger>
          <TabsTrigger value="booths">Booth Priorities</TabsTrigger>
          <TabsTrigger value="visitors">Visitor Prep</TabsTrigger>
        </TabsList>

        <TabsContent value="d2d">
          {!insight && !insightLoading ? (
            <EmptyState
              title="No insights yet"
              description="Run D2D mining to analyse the last week of door-to-door survey feedback."
            />
          ) : (
            <>
              <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
                <KpiCard label="Net sentiment" value={`${shift?.current.netPct ?? 0}%`} />
                <KpiCard
                  label="Shift vs prior period"
                  value={`${(shift?.deltaNetPct ?? 0) > 0 ? '+' : ''}${shift?.deltaNetPct ?? 0}`}
                  sub={`${shift?.prior.netPct ?? 0}% previously`}
                />
                <KpiCard label="Responses" value={shift?.current.total ?? 0} />
                <KpiCard
                  label="Generated by"
                  value={insight?.generatedBy === 'ai' ? 'AI' : 'Heuristic'}
                  sub={insight ? new Date(insight.createdAt).toLocaleDateString() : undefined}
                />
              </div>

              <div className="mt-4 grid gap-4 lg:grid-cols-2">
                <div className="space-y-3">
                  <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
                    Themes
                  </h2>
                  {themes.length === 0 && (
                    <p className="text-sm text-muted-foreground">No free-text feedback in this window.</p>
                  )}
                  {themes.map((t) => (
                    <Card key={t.theme}>
                      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-base capitalize">{t.theme}</CardTitle>
                        <div className="flex items-center gap-2">
                          <Badge variant={sentimentVariant(t.sentiment)}>{t.sentiment}</Badge>
                          <Badge variant="muted">{t.count}</Badge>
                        </div>
                      </CardHeader>
                      <CardContent>
                        {(t.sampleQuotes ?? []).map((q, i) => (
                          <p key={i} className="border-l-2 border-muted pl-3 text-sm italic text-muted-foreground">
                            “{q}”
                          </p>
                        ))}
                      </CardContent>
                    </Card>
                  ))}
                </div>

                <div>
                  <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
                    Emerging issues
                  </h2>
                  <Card>
                    <CardContent className="p-0">
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead>Issue</TableHead>
                            <TableHead>Hotspots</TableHead>
                            <TableHead className="text-right">Growth</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {(insight?.emergingIssues ?? []).map((i) => (
                            <TableRow key={i.issue}>
                              <TableCell className="font-medium">
                                {i.issue}
                                <span className="ml-2 text-xs text-muted-foreground">
                                  {i.priorCount} → {i.count}
                                </span>
                              </TableCell>
                              <TableCell className="text-xs text-muted-foreground">
                                {i.areas.join(', ') || '—'}
                              </TableCell>
                              <TableCell className="text-right">
                                <Badge variant={i.growth >= 50 ? 'danger' : i.growth > 0 ? 'warning' : 'muted'}>
                                  {i.growth > 0 ? '+' : ''}
                                  {i.growth}%
                                </Badge>
                              </TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </>
          )}
        </TabsContent>

        <TabsContent value="booths">
          <Card>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Booth</TableHead>
                    <TableHead>Village</TableHead>
                    <TableHead className="w-[320px]">Risk factors</TableHead>
                    <TableHead className="text-right">Risk</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {(booths?.data ?? []).map((b) => (
                    <TableRow key={b.boothId}>
                      <TableCell className="font-medium">
                        {b.number}
                        {b.name ? ` · ${b.name}` : ''}
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {b.village ?? '—'}
                        {b.mandal ? ` · ${b.mandal}` : ''}
                      </TableCell>
                      <TableCell>
                        {b.factors.map((f) => (
                          <FactorBar key={f.key} label={f.label} value={f.value} weight={f.weight} />
                        ))}
                      </TableCell>
                      <TableCell className="text-right">
                        <Badge variant={riskVariant(b.riskScore)}>{b.riskScore}</Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button size="sm" variant="outline" onClick={() => openDrawer(b)}>
                          Explain
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              {booths?.data?.length === 0 && (
                <EmptyState title="No booths in scope" description="Booth data is required to score risk." />
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="visitors">
          {visitors?.items?.length ? (
            <div className="space-y-3">
              {visitors.items.map((v) => (
                <Card key={`${v.kind}-${v.id}`}>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-base">
                      {v.name}
                      <span className="ml-2 text-xs font-normal text-muted-foreground">{v.purpose}</span>
                    </CardTitle>
                    <div className="flex items-center gap-2">
                      {v.at && (
                        <span className="text-xs text-muted-foreground">
                          {new Date(v.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </span>
                      )}
                      <Badge variant={v.kind === 'appointment' ? 'info' : 'muted'}>{v.kind}</Badge>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="whitespace-pre-line text-sm">
                      {v.brief ?? 'No matching citizen record — no brief available.'}
                    </p>
                  </CardContent>
                </Card>
              ))}
            </div>
          ) : (
            <EmptyState title="Nobody scheduled today" description="Confirmed appointments and check-ins appear here." />
          )}
        </TabsContent>
      </Tabs>

      <Dialog open={!!openBooth} onOpenChange={(o) => !o && setOpenBooth(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              Booth {openBooth?.number} · risk {openBooth?.riskScore}
            </DialogTitle>
            <DialogDescription>
              {openBooth?.village ?? ''}
              {openBooth?.mandal ? ` · ${openBooth.mandal}` : ''}
            </DialogDescription>
          </DialogHeader>
          {openBooth?.factors.map((f) => (
            <FactorBar key={f.key} label={f.label} value={f.value} weight={f.weight} />
          ))}
          <p className="whitespace-pre-line text-sm">
            {explain.isPending ? 'Generating explanation…' : (explain.data?.explanation ?? '')}
          </p>
        </DialogContent>
      </Dialog>
    </>
  );
}
