import {
  LayoutDashboard,
  Users,
  UserCog,
  MessageSquareWarning,
  Building2,
  HandCoins,
  MessageCircle,
  CalendarDays,
  ClipboardList,
  Map,
  HardHat,
  BrainCircuit,
  BarChart3,
  Bell,
  Settings,
  Activity as ActivityIcon,
  Phone,
  PhoneCall,
  Users2,
  Mail,
  CalendarClock,
  ListTodo,
  History,
  FileBarChart,
  Network,
  Eye,
  Crown,
  Megaphone,
  Newspaper,
  Boxes,
  ClipboardCheck,
  FileClock,
  GitMerge,
  ShieldAlert,
  AlertTriangle,
  UserCheck2,
  BarChart2,
  Home,
  UserCheck,
  MapPin,
  UserPlus,
  LineChart,
  FileSpreadsheet,
  FileText,
  Vote,
  Wallet,
  Hammer,
  Truck,
  MapPinned,
  UsersRound,
  Package,
  Radio,
  BellRing,
  AlarmClock,
  type LucideIcon,
} from 'lucide-react';
import { ModuleKey } from '@praja/types';
import { ASSET_CONFIG_LIST } from './asset-config';

export interface NavChild {
  label: string;
  href: string;
  icon: LucideIcon;
}

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  module: ModuleKey;
  group: 'Overview' | 'CRM' | 'Assets' | 'Service Delivery' | 'Engagement' | 'Election' | 'Activities' | 'Intelligence' | 'System';
  children?: NavChild[];
}

export const NAV_ITEMS: NavItem[] = [
  { label: 'Dashboard', href: '/dashboard', icon: LayoutDashboard, module: ModuleKey.Dashboard, group: 'Overview' },
  { label: 'War Room', href: '/war-room', icon: Radio, module: ModuleKey.WarRoom, group: 'Overview',
    children: [
      { label: 'Command Center', href: '/war-room', icon: LayoutDashboard },
      { label: 'Alerts', href: '/war-room/alerts', icon: ShieldAlert },
      { label: 'Escalations', href: '/war-room/escalations', icon: MessageSquareWarning },
      { label: 'Readiness', href: '/war-room/readiness', icon: MapPin },
      { label: 'Briefings', href: '/war-room/briefings', icon: FileBarChart },
    ],
  },
  { label: 'Cadre', href: '/cadre', icon: UserCog, module: ModuleKey.Cadre, group: 'CRM' },
  {
    label: 'Committees & Network',
    href: '/committees',
    icon: Network,
    module: ModuleKey.Committees,
    group: 'CRM',
    children: [
      { label: 'Mandal Committee', href: '/committees/mandal-committee', icon: Users2 },
      { label: 'Village Committee', href: '/committees/village-committee', icon: Users2 },
      { label: 'Coordination Committee', href: '/committees/coordination-committee', icon: Users2 },
      { label: 'Mandal Coordination Committee', href: '/committees/mandal-coordination-committee', icon: Users2 },
      { label: 'Mandal Observers', href: '/committees/observers', icon: Eye },
      { label: 'IMP Leaders', href: '/committees/imp-leaders', icon: Crown },
      { label: 'Influencers', href: '/committees/influencers', icon: Megaphone },
      { label: 'Press', href: '/committees/press', icon: Newspaper },
    ],
  },
  { label: 'Citizens', href: '/citizens', icon: Users, module: ModuleKey.Citizens, group: 'CRM' },
  {
    label: 'Assets',
    href: '/assets',
    icon: Boxes,
    module: ModuleKey.Assets,
    group: 'Assets',
    children: [
      { label: 'Assets Overview', href: '/assets', icon: Boxes },
      ...ASSET_CONFIG_LIST.map((c) => ({
        label: c.label,
        href: `/assets/${c.slug}`,
        icon: c.icon,
      })),
    ],
  },
  { label: 'Grievances', href: '/grievances', icon: MessageSquareWarning, module: ModuleKey.Grievances, group: 'Service Delivery' },
  { label: 'SLA Tracker', href: '/grievances/sla-tracker', icon: AlarmClock, module: ModuleKey.Grievances, group: 'Service Delivery' },
  {
    label: 'Temp Grievances',
    href: '/temp-grievances',
    icon: FileClock,
    module: ModuleKey.TempGrievances,
    group: 'Service Delivery',
    children: [
      { label: 'Dashboard', href: '/temp-grievances', icon: LayoutDashboard },
      { label: 'All Temp Grievances', href: '/temp-grievances/list', icon: ClipboardList },
      { label: 'Validation Queue', href: '/temp-grievances/validation-queue', icon: UserCheck2 },
      { label: 'Duplicate Review', href: '/temp-grievances/duplicates', icon: GitMerge },
      { label: 'Archived / Rejected', href: '/temp-grievances/archived', icon: ShieldAlert },
      { label: 'By Source', href: '/temp-grievances/by-source', icon: MessageCircle },
      { label: 'Validator Performance', href: '/temp-grievances/validators', icon: BarChart2 },
      { label: 'Reports', href: '/temp-grievances/reports', icon: FileSpreadsheet },
    ],
  },
  { label: 'Officials', href: '/officials', icon: Building2, module: ModuleKey.Officials, group: 'Service Delivery' },
  { label: 'Schemes', href: '/schemes', icon: HandCoins, module: ModuleKey.Schemes, group: 'Service Delivery' },
  { label: 'WhatsApp', href: '/whatsapp', icon: MessageCircle, module: ModuleKey.Whatsapp, group: 'Engagement' },
  { label: 'Events', href: '/events', icon: CalendarDays, module: ModuleKey.Events, group: 'Engagement' },
  { label: 'Surveys', href: '/surveys', icon: ClipboardList, module: ModuleKey.Surveys, group: 'Engagement' },
  {
    label: 'D2D Survey',
    href: '/d2d',
    icon: ClipboardCheck,
    module: ModuleKey.D2D,
    group: 'Engagement',
    children: [
      { label: 'Survey Dashboard', href: '/d2d/dashboard', icon: LayoutDashboard },
      { label: 'Create Survey', href: '/d2d/create', icon: ClipboardList },
      { label: 'Active Surveys', href: '/d2d/active', icon: ActivityIcon },
      { label: 'Household Survey', href: '/d2d/household', icon: Home },
      { label: 'Voter Survey', href: '/d2d/voter', icon: UserCheck },
      { label: 'Booth Survey', href: '/d2d/booth', icon: MapPin },
      { label: 'Volunteer Assignment', href: '/d2d/volunteers', icon: UserPlus },
      { label: 'Survey Responses', href: '/d2d/responses', icon: MessageSquareWarning },
      { label: 'Survey Analytics', href: '/d2d/analytics', icon: LineChart },
      { label: 'Survey Reports', href: '/d2d/reports', icon: FileSpreadsheet },
    ],
  },
  { label: 'GIS Map', href: '/gis', icon: Map, module: ModuleKey.Gis, group: 'Engagement' },
  { label: 'Dev Projects', href: '/projects', icon: HardHat, module: ModuleKey.DevProjects, group: 'Engagement' },
  { label: 'Attendance & GPS', href: '/attendance', icon: MapPin, module: ModuleKey.Attendance, group: 'Engagement',
    children: [
      { label: 'Dashboard', href: '/attendance', icon: LayoutDashboard },
      { label: 'Records', href: '/attendance/records', icon: ClipboardList },
      { label: 'Corrections', href: '/attendance/corrections', icon: FileClock },
      { label: 'Field Reports', href: '/attendance/field-reports', icon: FileBarChart },
      { label: 'Geo Zones', href: '/attendance/geo-zones', icon: MapPinned },
    ],
  },
  {
    label: 'Fundraising',
    href: '/fundraising',
    icon: Wallet,
    module: ModuleKey.Fundraising,
    group: 'Engagement',
    children: [
      { label: 'Dashboard', href: '/fundraising', icon: LayoutDashboard },
      { label: 'Donors', href: '/fundraising/donors', icon: Users },
      { label: 'Donations', href: '/fundraising/donations', icon: HandCoins },
      { label: 'Events', href: '/fundraising/events', icon: CalendarDays },
      { label: 'Follow-ups', href: '/fundraising/follow-ups', icon: Bell },
    ],
  },
  { label: 'Call Center', href: '/call-center', icon: Phone, module: ModuleKey.CallCenter, group: 'Engagement',
    children: [
      { label: 'Console', href: '/call-center/console', icon: LayoutDashboard },
      { label: 'Queues', href: '/call-center/queue', icon: ListTodo },
      { label: 'Call Logs', href: '/call-center/calls', icon: PhoneCall },
      { label: 'Scripts', href: '/call-center/scripts', icon: FileText },
      { label: 'Analytics', href: '/call-center/analytics', icon: BarChart2 },
    ],
  },
  {
    label: 'Leader Office',
    href: '/leader-office',
    icon: Crown,
    module: ModuleKey.LeaderOffice,
    group: 'Engagement',
    children: [
      { label: 'Dashboard', href: '/leader-office', icon: LayoutDashboard },
      { label: 'Appointments', href: '/leader-office/appointments', icon: CalendarClock },
      { label: 'Calendar', href: '/leader-office/calendar', icon: CalendarDays },
      { label: 'Visitors', href: '/leader-office/visitors', icon: Users },
      { label: 'VIP Contacts', href: '/leader-office/vip', icon: Crown },
    ],
  },
  { label: 'Activities', href: '/activities', icon: ActivityIcon, module: ModuleKey.Activities, group: 'Activities' },
  {
    label: 'Election Management',
    href: '/election',
    icon: Vote,
    module: ModuleKey.Election,
    group: 'Election',
    children: [
      { label: 'Election Dashboard', href: '/election/dashboard', icon: LayoutDashboard },
      { label: 'Election Expenses', href: '/election/expenses', icon: Wallet },
      { label: 'Campaign Works', href: '/election/works', icon: Hammer },
      { label: 'Vehicle Tracker', href: '/election/vehicles', icon: Truck },
      { label: 'Booth Management', href: '/election/booths', icon: MapPinned },
      { label: 'Voter Outreach', href: '/election/voter-outreach', icon: PhoneCall },
      { label: 'Campaign Teams', href: '/election/teams', icon: UsersRound },
      { label: 'Material Management', href: '/election/materials', icon: Package },
      { label: 'Polling Day Management', href: '/election/polling-day', icon: Radio },
      { label: 'Election Reports', href: '/election/reports', icon: FileSpreadsheet },
    ],
  },
  {
    label: 'Compliance',
    href: '/compliance',
    icon: ShieldAlert,
    module: ModuleKey.Compliance,
    group: 'Election',
    children: [
      { label: 'Dashboard', href: '/compliance', icon: LayoutDashboard },
      { label: 'Permissions', href: '/compliance/permissions', icon: ClipboardCheck },
      { label: 'Checklists', href: '/compliance/checklists', icon: ClipboardList },
      { label: 'Legal Notices', href: '/compliance/notices', icon: FileSpreadsheet },
      { label: 'Documents', href: '/compliance/documents', icon: FileText },
      { label: 'Alerts', href: '/compliance/alerts', icon: Bell },
    ],
  },
  {
    label: 'Manifesto Tracker',
    href: '/manifesto',
    icon: ClipboardList,
    module: ModuleKey.Manifesto,
    group: 'Election',
    children: [
      { label: 'Dashboard', href: '/manifesto', icon: LayoutDashboard },
      { label: 'Promises', href: '/manifesto/promises', icon: ClipboardList },
      { label: 'Categories', href: '/manifesto/categories', icon: ClipboardCheck },
      { label: 'Departments', href: '/manifesto/departments', icon: Building2 },
    ],
  },
  {
    label: 'Crisis Management',
    href: '/crisis',
    icon: ShieldAlert,
    module: ModuleKey.Crisis,
    group: 'Election',
    children: [
      { label: 'Dashboard', href: '/crisis', icon: LayoutDashboard },
      { label: 'Issues', href: '/crisis/issues', icon: AlertTriangle },
      { label: 'Heatmap', href: '/crisis/heatmap', icon: Map },
      { label: 'Escalations', href: '/crisis/escalations', icon: MessageSquareWarning },
      { label: 'RRT Teams', href: '/crisis/rrt', icon: UsersRound },
    ],
  },
  { label: 'Calls', href: '/activities/calls', icon: Phone, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Campaign Calls', href: '/activities/campaign-calls', icon: PhoneCall, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Conference Calls', href: '/activities/conference-calls', icon: Users2, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Emails', href: '/activities/emails', icon: Mail, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Meetings / Visits', href: '/activities/meetings', icon: CalendarClock, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Tasks', href: '/activities/tasks', icon: ListTodo, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Calendar', href: '/activities/calendar', icon: CalendarDays, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Activity Timeline', href: '/activities/timeline', icon: History, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'Activity Reports', href: '/activities/reports', icon: FileBarChart, module: ModuleKey.Activities, group: 'Activities' },
  { label: 'AI Command', href: '/ai', icon: BrainCircuit, module: ModuleKey.Ai, group: 'Intelligence' },
  {
    label: 'Voter Intelligence',
    href: '/voter-intelligence',
    icon: UserCheck,
    module: ModuleKey.VoterIntelligence,
    group: 'Intelligence',
    children: [
      { label: 'Dashboard', href: '/voter-intelligence', icon: LayoutDashboard },
      { label: 'Profiles', href: '/voter-intelligence/profiles', icon: Users },
      { label: 'Booth Strength', href: '/voter-intelligence/booths', icon: MapPin },
      { label: 'Families', href: '/voter-intelligence/families', icon: Home },
      { label: 'Duplicates', href: '/voter-intelligence/duplicates', icon: GitMerge },
      { label: 'Segments', href: '/voter-intelligence/segments', icon: BarChart2 },
      { label: 'Import Roll', href: '/voter-intelligence/import', icon: FileSpreadsheet },
    ],
  },
  { label: 'Reports', href: '/reports', icon: BarChart3, module: ModuleKey.Reports, group: 'Intelligence' },
  {
    label: 'Media Monitoring',
    href: '/media',
    icon: Newspaper,
    module: ModuleKey.Media,
    group: 'Intelligence',
    children: [
      { label: 'Dashboard', href: '/media', icon: LayoutDashboard },
      { label: 'News', href: '/media/news', icon: Newspaper },
      { label: 'Clippings', href: '/media/clippings', icon: FileText },
      { label: 'Mentions', href: '/media/mentions', icon: Megaphone },
      { label: 'Attacks', href: '/media/attacks', icon: ShieldAlert },
      { label: 'Responses', href: '/media/responses', icon: MessageCircle },
      { label: 'Reputation', href: '/media/reputation', icon: LineChart },
      { label: 'PR Command Center', href: '/media/pr', icon: BrainCircuit },
      { label: 'PR Reports', href: '/media/pr/reports', icon: FileBarChart },
      { label: 'PR Alerts', href: '/media/pr/alerts', icon: BellRing },
      { label: 'News Sources', href: '/media/pr/sources', icon: Radio },
    ],
  },
  { label: 'Data Quality', href: '/data-quality', icon: GitMerge, module: ModuleKey.DataQuality, group: 'Intelligence',
    children: [
      { label: 'Dashboard', href: '/data-quality', icon: LayoutDashboard },
      { label: 'Issues', href: '/data-quality/issues', icon: ShieldAlert },
      { label: 'Merges', href: '/data-quality/merges', icon: GitMerge },
      { label: 'Normalization', href: '/data-quality/normalization', icon: FileSpreadsheet },
    ],
  },
  { label: 'Documents', href: '/documents', icon: FileSpreadsheet, module: ModuleKey.Documents, group: 'Intelligence',
    children: [
      { label: 'Dashboard', href: '/documents', icon: LayoutDashboard },
      { label: 'Library', href: '/documents/library', icon: FileText },
      { label: 'Categories', href: '/documents/categories', icon: ClipboardList },
    ],
  },
  { label: 'Notifications', href: '/notifications', icon: Bell, module: ModuleKey.Notifications, group: 'System' },
  { label: 'Offline Sync', href: '/offline-sync', icon: History, module: ModuleKey.OfflineSync, group: 'System',
    children: [
      { label: 'Dashboard', href: '/offline-sync', icon: LayoutDashboard },
      { label: 'Pending Queue', href: '/offline-sync/pending', icon: ListTodo },
      { label: 'Conflicts', href: '/offline-sync/conflicts', icon: GitMerge },
    ],
  },
  { label: 'Security Audit', href: '/security-audit', icon: ShieldAlert, module: ModuleKey.SecurityAudit, group: 'System',
    children: [
      { label: 'Dashboard', href: '/security-audit', icon: LayoutDashboard },
      { label: 'Login History', href: '/security-audit/logins', icon: History },
      { label: 'Sessions', href: '/security-audit/sessions', icon: UserCheck2 },
      { label: 'Export Logs', href: '/security-audit/exports', icon: FileSpreadsheet },
      { label: 'File Access', href: '/security-audit/file-access', icon: Eye },
      { label: 'Alerts', href: '/security-audit/alerts', icon: ShieldAlert },
    ],
  },
  { label: 'Settings', href: '/settings', icon: Settings, module: ModuleKey.Admin, group: 'System' },
];

export const NAV_GROUP_ORDER: NavItem['group'][] = [
  'Overview',
  'CRM',
  'Assets',
  'Service Delivery',
  'Engagement',
  'Election',
  'Activities',
  'Intelligence',
  'System',
];

export function pageTitle(pathname: string): string {
  const childMatches = NAV_ITEMS.flatMap((i) =>
    (i.children ?? []).map((c) => ({ label: c.label, href: c.href })),
  );
  const all = [
    ...NAV_ITEMS.map((i) => ({ label: i.label, href: i.href })),
    ...childMatches,
  ];
  const matches = all.filter((i) => pathname === i.href || pathname.startsWith(i.href + '/'));
  const best = matches.sort((a, b) => b.href.length - a.href.length)[0];
  return best?.label ?? 'Praja Connect';
}
